name: 'PR Submodule Dependencies'
description: 'Pull in changes on submodules which are required by a pull request'
branding:
  icon: git-pull-request
  color: blue
inputs:
  map:
    description: "JSON mapping of repository name to local directory path overrides"
    required: false
    default: "{}"
runs:
  using: 'node24'
  main: 'dist/index.js'
